language: python

env:
  - PYTHON_VERSION=3.6

before_install:
  - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda
install:
    - conda create -n testenv --yes pip python=${PYTHON_VERSION}
    - source activate testenv
    - conda install --yes --quiet numpy=1.11 matplotlib=1.5 scipy=0.19 numba
    - conda install --yes --quiet pytest coverage
    - pip install flake8 check-manifest
    - pip install mne coverage coveralls
    - python setup.py develop --no-deps
script:
    - make
after_success:
  - bash <(curl -s https://codecov.io/bash)
